spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:utfparking;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    database: H2
    show-sql: true
    hibernate:
      ddl-auto: update
      database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        use_sql_comments: true
        format_sql: true
server:
  port: 9999
